### ISSUE TITLE
CreateContainer() in trunk generates an invalid assembly

### ISSUE THREAD

**Issue by unintelligible** [philiplaureano/Hiro#1]
Steps to reproduce:
1. clone current github rep locally
2. modify Hiro.DependencyMap and add the following belo line 277 (in the CreateContainer method):   <code>assembly.Write("D:\test.dll");</code>
3. inspect the resulting DLL in peverify.exe

The output of peverify is as follows:

<pre>
 [IL]: Error: [C:\code\thirdparty\hiro-git\Hiro-Vanilla\Hiro\build\Debug\UnitTests\test.dll : Hiro.Containers.MicroContainer::GetInstance][offset 0x000001A7] Stack must contain only the return value.
1 Error(s) Verifying C:\code\thirdparty\hiro-git\Hiro-Vanilla\Hiro\build\Debug\UnitTests\test.dll
</pre>

Note: all unit tests pass, but I think this issue what is causing the error mentioned here: https://github.com/kkozmic/PaulTest/commit/5650add9137336c0ccd5d8a00a9bf99f90517f77

**Comment by philiplaureano** [comment]
Fixed in the latest build -https://github.com/philiplaureano/Hiro/commit/5de4a05c13dfd469a8815f0d1bdeba81ecdb1e92

Try it out and let me know if it works for you. Thanks

**Comment by unintelligible** [comment]
Thanks very much for the fix - I just checked and it works great.
