### ISSUE TITLE
Use in v4.0 framework - compilier errors

### ISSUE THREAD

**Issue by jasonlaflair** [philiplaureano/Hiro#4]
We using nuget to use Hiro (1.0.3) I'm now getting the following compiler errors and warnings

Error   1   Missing compiler required member 'System.Runtime.CompilerServices.ExtensionAttribute..ctor' 
Warning 6   The predefined type 'System.Action' is defined in multiple assemblies in the global alias; using definition from 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\mscorlib.dll'
Warning 10  The predefined type 'System.Func' is defined in multiple assemblies in the global alias; using definition from 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\mscorlib.dll'
Warning 5   The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'c:\Development...\packages\Hiro.1.0.3\lib\Hiro.dll' 

The library it's being use in is a v4.0 (non client profile) class library.

I saw this in another project that utilizes Mono.Cecil - Gallio - here is the ticket and discussions of their solution.

http://code.google.com/p/mb-unit/issues/detail?id=784

**Comment by philiplaureano** [comment]
Have you tried building Hiro from the trunk?

**Comment by jasonlaflair** [comment]
Yes, pulled it down on 8/1/11 - used the go.bat to do the build and used the Hiro.dll from the build directory and Hiro.Containers from build/Debug.

**Comment by philiplaureano** [comment]
Do you have ILMerge installed?

**Comment by jasonlaflair** [comment]
Yes, I'm getting the same issues if I use the ILMerge output or just use the pre-merge references.

**Comment by philiplaureano** [comment]
Have you tried using the release version?

**Comment by jasonlaflair** [comment]
Which do you classify as "release version"?  I've tried all from nuget and anything after v1.0 seems to have this issue (post a Mono.Cecil update)

**Comment by philiplaureano** [comment]
Try: https://github.com/downloads/philiplaureano/Hiro/Hiro-release_v1.01.zip

What DLL are you compiling it with that is causing the conflict? Hiro
internalizes all of its external references with ILMerge and it works fine
before the Mono.Cecil update. I have tried pulling down a fresh copy of Hiro
from github on two separate laptops and it builds fine with .NET 4
installed, so I can't reproduce the error.

**Comment by jasonlaflair** [comment]
Ya, anything prior to the Mono.Cecil update seems to work fine....  the initial issue I posted was from 1.0.3 from nuget.  using 1.0.1 seems to just throw compiler warnings and no errors.

**Comment by philiplaureano** [comment]
Just stick with the version that Hiro is working with--I hate to do this,
but I'm definitely not going to clean up Jb's mess.

(Note: This is another reason why I'm writing my own IL reader/writer
library)

**Comment by jasonlaflair** [comment]
Sounds good.
